// SPDX-License-Identifier: MIT
pragma solidity ^0.8.23;

import "@semaphore-protocol/contracts/interfaces/ISemaphore.sol";

/**
 * @title ExamGroup
 * @notice Minimal Solidity contract for managing Semaphore V4 group membership
 *         in an anonymous university exam eligibility system.
 */
contract ExamGroup {
    ISemaphore public immutable semaphore;
    uint256 public immutable groupId;
    address public immutable admin;

    // Track local array of commitments for getMembers helper
    uint256[] private commitments;

    event StudentJoinedGroup(uint256 indexed groupId, uint256 identityCommitment, uint256 newMemberCount);

    /**
     * @param _semaphoreAddress Address of the deployed Semaphore V4 contract on network
     *        (e.g., Sepolia: 0x8A1fd199516489B0Fb7153EB5f075cDAC83c693D)
     */
    constructor(address _semaphoreAddress) {
        require(_semaphoreAddress != address(0), "Invalid Semaphore address");
        semaphore = ISemaphore(_semaphoreAddress);
        admin = msg.sender;

        // Create a new Semaphore group with contract as admin
        // Note: Semaphore V4 createGroup returns a uint256 groupId
        groupId = semaphore.createGroup();
    }

    /**
     * @notice Adds a student's public Semaphore Identity Commitment leaf to the group.
     * @dev NOTE FOR PRODUCTION: In production, eligibility would be verified on-chain
     *      via a signed ZK Email / Anon Aadhaar credential or Merkle allowlist proof.
     *      For this demo, eligibility is confirmed by the frontend Step 1 Web2 gate.
     * @param identityCommitment The public 256-bit commitment generated by student identity.
     */
    function join(uint256 identityCommitment) external {
        require(identityCommitment != 0, "Invalid commitment");

        // Call standard Semaphore protocol contract to append member
        semaphore.addMember(groupId, identityCommitment);
        commitments.push(identityCommitment);

        emit StudentJoinedGroup(groupId, identityCommitment, commitments.length);
    }

    /**
     * @notice Returns all member commitments in this group.
     * @dev Used by frontend to dynamically reconstruct the Merkle Tree before proof generation.
     */
    function getMembers() external view returns (uint256[] memory) {
        return commitments;
    }

    /**
     * @notice Returns total members count
     */
    function getMembersCount() external view returns (uint256) {
        return commitments.length;
    }
}
